### ISSUE TITLE
[Bug] .private_core/com.metacubex.ClashX.ProxyConfigHelper.meta 文件更新频繁导致防火墙提示频繁

### ISSUE THREAD

**Issue by coderbean** [MetaCubeX/ClashX.Meta#31]
感谢你向 ClashX 提交 issue！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [x] 这是 ClashX UI层面的问题，并非 Clash Core 的问题(例如xx软件连不上，无法连接特定服务器等)。其他 Clash 衍生版本没有次问题。
- [x] 如果你可以自己 debug 并解决的话，提交 PR 吧！

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### clashX config

```
……
```

### ClashX log

```
……
```

### ClashX Crash log

```
……
```

### 环境 Environment
……
* 使用者的操作系统 (the OS running on the client)
MacOS
……
* 网路环境或拓扑 (network conditions/topology)
……
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
……
* 其他
……

### 重现问题的具体布骤 Steps to Reproduce

打开软件会会提示防火墙确认，如果退出后重新打开会再次提示。不是会提示一次，尝试自己给对应的文件签名，可以发现这个文件每次都是新的，也看了源代码，没有找到这个文件是从哪里来的。
<img width="274" alt="image" src="https://github.com/MetaCubeX/ClashX.Meta/assets/10681146/880dbdb3-6454-4168-b220-de28419c57da">

**我预期会发生……？**

第一次打开提示防火墙，以后不再提示防火墙，或者内核更新了再提示防火墙。
目前看到的现象是，内核没有更新，还是会临时创建这个文件。是不是可以做到没有更新就不懂这个文件，下次直接用
文件路径：~/Library/Application\ Support/com.metacubex.ClashX.meta/.private_core/com.metacubex.ClashX.ProxyConfigHelper.meta
**实际上发生了什麽？**

**Comment by mrFq1** [comment]
内核文件由Github Actions 自动下载于 
[MetaCubeX/Clash.Meta release](https://github.com/MetaCubeX/Clash.Meta/releases)
内核更新release 或者修复重要bug  都会同步更新一个新版

**Comment by deckvig** [comment]
+1，使用 wireguard 后，每次启动 clash meta 都会弹窗提示需要授权防火墙

**Comment by deckvig** [comment]
> +1，使用 wireguard 后，每次启动 clash meta 都会弹窗提示需要授权防火墙

Update: 更新使用最新的 Alpha 内核解决了

**Comment by alreadysearched** [comment]
<img width="1341" alt="image" src="https://github.com/MetaCubeX/ClashX.Meta/assets/47503860/691e1207-75fd-4a5f-8d3f-b9b3049b4827">


Facing the same issue by the system firewall.

Version:v1.3.6(456)
Meta Core: v1.16.0
macOs Sonoma 14.0

**Comment by alreadysearched** [comment]
<img width="612" alt="image" src="https://github.com/MetaCubeX/ClashX.Meta/assets/47503860/7a0e1d2e-b45a-4d3e-b399-0b21a1c2edfb">

Use alpha meta and then restart the app and the computer, the firewall no longer prompts this issue.
